### ISSUE TITLE
could you please export ITokenResponse interface from PKCE.d.ts ?

### ISSUE THREAD

**Issue by yarick123** [bpedroza/js-pkce#15] opened 2022-01-06 12:08 UTC
could you please export **ITokenResponse** interface from PKCE.d.ts ?

Now I have to copy **ITokenResponse** interface to my codebase if I need to process the responce in a method other that calls **pkce.exchangeForAccessToken(..)**

Thank you in advance

**Comment by yarick123** [comment] 2022-01-06 12:14
or just to put all ***.d.ts** files including **ITokenResponse.d.ts** to folder dist/ of the npm package...

**Comment by yarick123** [comment] 2022-01-06 14:34
P.S. could you please also extend ITokenResponse with
`id_token: string;`
?

**Comment by bpedroza** [comment] 2022-02-24 20:06
This is a duplicate of #12 closing

**Closed by bpedroza** 2022-02-24 20:06 UTC
